### ISSUE TITLE
UHR RFID Reader

### ISSUE THREAD

**Issue by Danimat83** [stijnsprojects/RFID_time_logger#1]
Which Reader is used for this Project? 

And can you share the settings for the reader?

Thx

**Comment by stijnsprojects** [comment]
I used the cheapest chinese UHF RFID reader I could find at the time (https://www.amazon.de/gp/product/B08PV1WBKL), I think they are all pretty much the same because they all look the same. Here are the settings I used.
![im1](https://github.com/stijnsprojects/RFID_time_logger/assets/111092317/b051810a-8290-41cb-8fab-78b0e6654ccc)
![im2](https://github.com/stijnsprojects/RFID_time_logger/assets/111092317/a5e86cdb-97ca-4f4c-a485-2ee12efa13e9)
![im3](https://github.com/stijnsprojects/RFID_time_logger/assets/111092317/1193be09-38d7-49f2-bc7e-35ea9962eaa3)
